name: Upload Python Package

on:
  create:
    tags:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get all git tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[develop]
        pip install setuptools wheel twine
    - name: Install pandoc
      run: |
        sudo apt-get install -y --no-install-recommends pandoc
    - name: Build documentation
      run: |
        tox -e docs
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
    - name: Build and publish package to pypi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        tox -e build
        twine upload dist/*
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*,docs/notebooks/analysis_flanders.ipynb"
        omitBody: true
